name: CI-Development

on:

  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]


  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: |
          cd /home/runner/work/health-center-page/health-center-page/frontend
          npm install
          npm ci
      - name: Print current working directory
        run: pwd
      - name: Run lint tests
        run: |
          cd /home/runner/work/health-center-page/health-center-page/frontend
          npm run lint
      - name: Setup .NET Core environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x'
      - name: Build and test backend
        working-directory: backend
        run:  |
          dotnet build
          dotnet test
